# Generated by Django 4.1.2 on 2023-07-05 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('loc_id', models.AutoField(primary_key=True, serialize=False)),
                ('loc_name', models.CharField(max_length=30)),
                ('loc_limit', models.CharField(max_length=10)),
                ('loc_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ad',
            fields=[
                ('ad_id', models.AutoField(primary_key=True, serialize=False)),
                ('ad_name', models.TextField()),
                ('ad_start', models.DateField()),
                ('ad_end', models.DateField()),
                ('ad_created', models.DateTimeField(auto_now=True)),
                ('ad_loc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.location')),
            ],
        ),
    ]
