# Generated by Django 4.1.2 on 2023-07-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='ad_visits',
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
