# Generated by Django 4.1.2 on 2023-07-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_ad_ad_visits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='ad_visits',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
