# Generated by Django 4.1.2 on 2023-07-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_ad_ad_visits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='ad_visits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='location',
            name='loc_limit',
            field=models.IntegerField(default=0),
        ),
    ]
